In [37]:
# Importar bibliotecas

import pandas as pd
import numpy as np
import plotly.express as px

from sklearn.model_selection import train_test_split
from sklearn.ensemble import AdaBoostRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import root_mean_squared_error, r2_score

In [38]:
# Carregar os dados
df_costs = pd.read_csv('datasets/healthcosts_cleaned.csv')

In [39]:
# Mostrar as primeiras linhas
df_costs.head(10)

   age     sex     bmi  children  smoker     region  medical charges
0   19  female  27.900         0       1  southwest      16884.92400
1   18    male  33.770         1       0  southeast       1725.55230
2   28    male  33.000         3       0  southeast       4449.46200
3   33    male  22.705         0       0  northwest      21984.47061
4   32    male  28.880         0       0  northwest       3866.85520
5   31  female  25.740         0       0  southeast       3756.62160
6   46  female  33.440         1       0  southeast       8240.58960
7   37  female  27.740         3       0  northwest       7281.50560
8   37    male  29.830         2       0  northeast       6406.41070
9   60  female  25.840         0       0  northwest      28923.13692

In [40]:
# Mostrar as últimas linhas
df_costs.tail(10)

      age     sex     bmi  children  smoker     region  medical charges
1328   23  female  24.225         2       0  northeast      22395.74424
1329   52    male  38.600         2       0  southwest      10325.20600
1330   57  female  25.740         2       0  southeast      12629.16560
1331   23  female  33.400         0       0  southwest      10795.93733
1332   52  female  44.700         3       0  southwest      11411.68500
1333   50    male  30.970         3       0  northwest      10600.54830
1334   18  female  31.920         0       0  northeast       2205.98080
1335   18  female  36.850         0       0  southeast       1629.83350
1336   21  female  25.800         0       0  southwest       2007.94500
1337   61  female  29.070         0       1  northwest      29141.36030

In [41]:
# Mostrar a estrutura
df_costs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   age              1338 non-null   int64
 1   sex              1338 non-null   object
 2   bmi              1338 non-null   float64
 3   children         1338 non-null   int64
 4   smoker           1338 non-null   int64
 5   region           1338 non-null   object
 6   medical charges  1338 non-null   float64
dtypes: float64(2), int64(3), object(2)
memory usage: 73.3+ KB

# Preparação dos dados

In [42]:
# Preparar os dados para o modelo
X = df_costs.drop(columns=['medical charges'])
y = df_costs['medical charges']

In [43]:
# Importar preprocessor já salvo anteriormente
import joblib
preprocessor = joblib.load('preprocessor_dataset_healthcosts.pkl')

In [44]:
# Dividir os dados em treinamento e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=51)

In [45]:
# Aplicar preprocessor nos dados de treinamento e teste
X_train = preprocessor.fit_transform(X_train)
X_test = preprocessor.transform(X_test)

In [46]:
# Mostrar as dimensões dos conjuntos
print(f'Dados de Treinamento: {X_train.shape}')
print(f'Dados de Teste: {X_test.shape}')

Dados de Treinamento: (1070, 10)
Dados de Teste: (268, 10)

# Treinamento do Modelo

In [77]:
# Criar o modelo de AdaBoost Regressor
boosting_model = AdaBoostRegressor(
    estimator=LinearRegression(),
    n_estimators=50,
    learning_rate=0.1,
    random_state=51
)

In [78]:
# Treinar o modelo
boosting_model.fit(X_train, y_train)

AdaBoostRegressor(estimator=LinearRegression(), learning_rate=0.1,
                  random_state=51)

# Análise dos Resultados

In [79]:
# Fazer predições no conjunto de testes
y_pred = boosting_model.predict(X_test)

In [80]:
# Mostrar y_pred
y_pred

array([10976.        , 37612.        ,  5012.93521639, 12765.00076501,
       34555.49924998, 12999.74799563, 13156.52947181, 16901.55092628,
        7744.        , 12640.        , 11358.1459602 , 13569.59966511,
       11520.        ,  6253.18413887,  6846.15958396, 14154.18198419,
        7670.43161232,  7217.98912424, 26525.82136294, 29036.30264288,
       12000.23933284, 10528.        , 33230.        , 14938.16413176,
        7447.92737838, 17696.        , 11513.71701492,  4768.        ,
       23471.60633861, 10052.57650688,  5920.        , 30836.93665273,
        7639.24864574,  6403.13043574,  9638.78991361, 12923.74178716,
       15333.53132246,  4336.13914346, 14229.58252536,  9851.23072431,
       11755.79385553,  2417.94299778,  7474.32034804,  4121.64499419,
        6047.80488374, 16718.22352656, 16912.81171564, 35948.17542038,
        9313.51307181, 14148.75500735,  7376.81323911, 31345.82909   ,
        9073.21359529, 40906.21777261,  5476.34472979, 28384.        ,
       12479.76184082, 12925.69506517, 14671.79416265, 10427.13597338,
       11072.        , 10794.33702784, 32763.25534301,  2171.89473684,
        8546.        , 14592.46517607, 15060.68956027,  6445.40323201,
       17408.        ,  8887.5777777 , 34758.83067559, 17079.81203951,
        8681.55453954,  3526.19078465, 14592.        , 12296.33135721,
       24813.13918711, 37706.60624996, 11449.59247192, 12408.73573928,
        3809.0035382 , 11545.91236541, 12326.04017589,  5536.        ,
        9046.38846127, 40455.11204554,  8960.        , 15104.        ,
       14964.55739038,  9527.41360235,  7664.94396329, 12400.58293133,
       10269.55581965,  4619.00305825,  9545.46395274, 28488.11683993,
       35559.6858407 , 15492.63453324, 29478.62032198,  8330.52659776,
        4317.09457253,  3309.33071576, 37177.3905819 , 10839.00001672,
        7400.13688404, 12269.9046526 , 11870.90171586, 11161.44332537,
       14982.5195739 , 32998.10278469, 10337.50463507,  7879.39451124,
        6336.        ,  6974.14379119, 13552.37137497, 14163.73289472,
        6848.        , 18769.94882897, 19373.7212702 , 38211.69602822,
       39989.04669812, 11516.01637371, 41430.38887363,  7584.        ,
        3446.99872855, 31036.03566289,  8081.84184617, 28278.        ,
       11965.78214451,  6227.52679948,  2311.80916099, 10208.        ,
          58.8532309 , 10310.6358771 ,  6560.        , 32480.        ,
        9089.11366746,  5411.93967552,  6048.        ,  8127.8645613 ,
       34060.06856031,  2532.04105108, 36501.65588201,  4672.        ,
       13669.15407913, 13931.9232948 , 10282.14363799, 32780.97583847,
       17305.98066813, 16598.54334193, 32416.        , 39512.6627559 ,
       12786.03767422, 11360.45356837,   145.8153107 , 18487.57358668,
       36449.10644986, 14784.        ,  6560.        ,  3697.86530543,
       37330.        , 28961.93696042, 30899.06032661,  9210.64566159,
       12320.        , 13541.46685967, 12592.16832956, 18768.9974412 ,
       30098.47964736,  6282.18726883,  3101.13000888,  9419.73426865,
       14240.        ,  5510.18169063, 32165.52765007, 36384.        ,
       10944.        , 34318.        , 16426.74329551,  8000.        ,
        6905.84735498,   449.21417129, 12918.27506996,  8802.00398546,
       11111.49719738,  8044.60009651, 18447.44747454, 10371.5738388 ,
        7204.128728  , 10132.59594175, 11365.85330972, 34380.23404202,
       11695.25370433, 32002.99413416, 12544.        ,  6309.25035475,
        5952.        , 31423.28846142, 12433.24726164, 12199.43628303,
        8874.96285135, 30574.        , 35460.51361413, 16677.2713513 ,
        9270.77662628,  3186.57563406, 17692.00506539, 17116.23326845,
       11392.        ,   871.45960695,  8130.57422189, 38338.39895362,
       15808.        , 14674.27186207,  7456.69920012, 30304.        ,
       17152.        , 38720.76527539, 31883.58289825,  8870.23963739,
       15264.        ,  9640.60617883, 13363.54160781,  5470.24018193,
        7341.99369062,  8128.        ,  9912.96019489,  5161.14511659,
        2585.07433466,  6484.6582857 ,  4827.38718882,  6626.12029513,
        8083.9444194 ,  3948.61410102,  3547.81766561, 19561.57894959,
       32080.29988668,  8544.        , 12480.        , 14560.        ,
        9218.79661537, 10179.6579256 , 11220.12680362,  3293.68618226,
       12455.20996821, 25518.55411493, 14182.10352103,  8308.94095165,
       27926.61638337, 15987.01366719,  3669.23176183,  6352.94051494,
       11984.28277388, 16144.32544709, 36366.26735718, 32544.        ,
       11875.43987881, 29896.41993138,  4942.63969239, 10603.3543585 ,
        8746.49873146, 12768.        , 39221.20933774, 14239.20697247,
       28953.36666634, 27043.29626205, 38627.133356  , 15674.94887694])

In [81]:
# Avaliar métricas do modelo
rmse = root_mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

In [82]:
# Mostrar as métricas
print(f'Root Mean Squared Error: {rmse}')
print(f'R2: {r2}')

Root Mean Squared Error: 6776.479230900867
R2: 0.7359098647707016

## Análise de importancia das features

In [83]:
# Calcular a importância das features usando os coeficientes

# Obter os coeficientes de cada estimador
coefs = np.array([estimator.coef_ for estimator in boosting_model.estimators_])

In [84]:
# Calcular média dos coeficientes absolutos
importances = np.mean(np.abs(coefs), axis=0)

In [85]:
# Normalizar as importâncias
importances = importances / np.sum(importances)

In [86]:
# Obter os nomes das features
feature_names = preprocessor.get_feature_names_out()

In [87]:
# Criar um DataFrame com as importâncias e os nomes das features
importance_df = pd.DataFrame({'feature': feature_names, 'importance': importances})

In [88]:
# Ordenar o DataFrame pela importância
importance_df = importance_df.sort_values('importance', ascending=True)

In [89]:
# Criar o gráfico de barras com a importância das features
fig = px.bar(importance_df,
             x='importance',
             y='feature',
             title='Importância das Features',
             orientation='h')

# fig.update_xaxes(tickangle=45)
fig.show()

# Propriedades do Modelo

In [90]:
# Quais foram os erros dos estimadores
boosting_model.estimator_errors_

array([0.13261321, 0.14178828, 0.13945046, 0.15740933, 0.15149962,
       0.1644491 , 0.16474001, 0.1676325 , 0.17836876, 0.18881481,
       0.19048031, 0.19066031, 0.19322675, 0.20531693, 0.21697667,
       0.21022059, 0.21494196, 0.23164484, 0.2310104 , 0.24199716,
       0.24903985, 0.25084348, 0.2591333 , 0.26771042, 0.30488533,
       0.28626092, 0.29762589, 0.28687927, 0.29702499, 0.30133027,
       0.32543678, 0.31196894, 0.32697554, 0.31564419, 0.37087937,
       0.32963035, 0.36215705, 0.34439344, 0.34570468, 0.35023888,
       0.39527036, 0.35869247, 0.37149859, 0.37045863, 0.42759561,
       0.38281458, 0.40230907, 0.3984117 , 0.36942582, 0.40315813])

In [91]:
# Pesos dos estimadores
boosting_model.estimator_weights_

array([0.18780483, 0.18005159, 0.18198617, 0.16776316, 0.17228874,
       0.16254902, 0.16233745, 0.16024999, 0.15274386, 0.14577297,
       0.14468923, 0.14457254, 0.14291783, 0.13533886, 0.12833726,
       0.13235963, 0.12953896, 0.11990467, 0.12026147, 0.11417611,
       0.11037397, 0.10941188, 0.10504781, 0.10062701, 0.08241411,
       0.09136138, 0.08586289, 0.09105893, 0.0861505 , 0.08409712,
       0.07288972, 0.07909304, 0.07218963, 0.07738624, 0.05284461,
       0.07098574, 0.05660141, 0.06437761, 0.06379739, 0.06179894,
       0.04252115, 0.05810437, 0.05257932, 0.05302498, 0.02916678,
       0.04776187, 0.03958532, 0.04120874, 0.05346808, 0.03923233])