In [1]:
# Importar bibliotecas

import pandas as pd
import numpy as np
import plotly.express as px

from sklearn.model_selection import train_test_split
from sklearn.ensemble import AdaBoostRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import root_mean_squared_error, r2_score

In [2]:
# Carregar os dados
df_costs = pd.read_csv('datasets/healthcosts_cleaned.csv')

In [3]:
# Mostrar as primeiras linhas
df_costs.head(10)

   age     sex     bmi  children  smoker     region  medical charges
0   19  female  27.900         0       1  southwest      16884.92400
1   18    male  33.770         1       0  southeast       1725.55230
2   28    male  33.000         3       0  southeast       4449.46200
3   33    male  22.705         0       0  northwest      21984.47061
4   32    male  28.880         0       0  northwest       3866.85520
5   31  female  25.740         0       0  southeast       3756.62160
6   46  female  33.440         1       0  southeast       8240.58960
7   37  female  27.740         3       0  northwest       7281.50560
8   37    male  29.830         2       0  northeast       6406.41070
9   60  female  25.840         0       0  northwest      28923.13692

In [4]:
# Mostrar as últimas linhas
df_costs.tail(10)

      age     sex     bmi  children  smoker     region  medical charges
1328   23  female  24.225         2       0  northeast      22395.74424
1329   52    male  38.600         2       0  southwest      10325.20600
1330   57  female  25.740         2       0  southeast      12629.16560
1331   23  female  33.400         0       0  southwest      10795.93733
1332   52  female  44.700         3       0  southwest      11411.68500
1333   50    male  30.970         3       0  northwest      10600.54830
1334   18  female  31.920         0       0  northeast       2205.98080
1335   18  female  36.850         0       0  southeast       1629.83350
1336   21  female  25.800         0       0  southwest       2007.94500
1337   61  female  29.070         0       1  northwest      29141.36030

In [5]:
# Mostrar a estrutura
df_costs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   age              1338 non-null   int64
 1   sex              1338 non-null   object
 2   bmi              1338 non-null   float64
 3   children         1338 non-null   int64
 4   smoker           1338 non-null   int64
 5   region           1338 non-null   object
 6   medical charges  1338 non-null   float64
dtypes: float64(2), int64(3), object(2)
memory usage: 73.3+ KB

# Preparação dos dados

In [12]:
# Preparar os dados para o modelo
X = df_costs.drop(columns=['medical charges'])
y = df_costs['medical charges']

In [13]:
# Importar preprocessor já salvo anteriormente
import joblib
preprocessor = joblib.load('preprocessor_dataset_healthcosts.pkl')

In [14]:
# Dividir os dados em treinamento e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=51)

In [15]:
# Aplicar preprocessor nos dados de treinamento e teste
X_train = preprocessor.fit_transform(X_train)
X_test = preprocessor.transform(X_test)

In [16]:
# Mostrar as dimensões dos conjuntos
print(f'Dados de Treinamento: {X_train.shape}')
print(f'Dados de Teste: {X_test.shape}')

Dados de Treinamento: (1070, 10)
Dados de Teste: (268, 10)

# Treinamento do Modelo

In [21]:
# Criar o modelo de AdaBoost Regressor
boosting_model = AdaBoostRegressor(
    estimator=LinearRegression(),
    n_estimators=50,
    learning_rate=1.0,
    random_state=51
)

In [22]:
# Treinar o modelo
boosting_model.fit(X_train, y_train)

AdaBoostRegressor(estimator=LinearRegression(), random_state=51)

# Análise dos Resultados

In [23]:
# Fazer predições no conjunto de testes
y_pred = boosting_model.predict(X_test)

In [24]:
# Mostrar y_pred
y_pred

array([10774.04557571, 37774.        ,  4901.62996501, 12515.77498084,
       34646.        , 13378.04764218, 13630.3409287 , 16871.11602794,
        7158.66042009, 12561.25281837, 11572.73802017, 13972.77994414,
       11852.7121236 ,  6334.65990676,  6776.5211331 , 14085.83213492,
        7804.50884461,  7502.06200229, 25832.84029631, 29200.35816502,
       13225.92018378, 10081.29512958, 33230.        , 14421.1869303 ,
        7609.01561891, 17246.9953249 , 11436.12286396,  5293.94888491,
       24150.        ,  9373.38126627,  6837.98108944, 31288.        ,
        8016.75381931,  6663.74075501,  9120.73263597, 12786.09711692,
       15444.52333991,  4105.15043784, 13716.00000053, 10109.9541843 ,
       11985.21945631,  2517.6040554 ,  7439.8185571 ,  4219.99449624,
        5631.70000421, 16483.23953707, 16993.05520135, 35442.        ,
        8636.94880467, 14427.18924098,  7848.89785755, 30878.        ,
        8215.30896603, 41258.        ,  5261.61220316, 27913.73373556,
       13193.93364445, 12271.83429583, 14896.15284709, 10705.4412084 ,
       10626.24570741, 11411.21575084, 32846.        ,  2046.94749213,
        7556.        , 15194.85846838, 15896.06586168,  6165.59649134,
       17204.16372846,  8596.02144794, 35397.03724423, 16663.24744982,
        9304.6648165 ,  2643.78289036, 13836.77355411, 12238.01469691,
       24600.        , 37518.        , 12461.5977309 , 11941.54437244,
        4329.59302366, 11446.59364699, 12286.19930357,  6341.71359572,
        8960.58413714, 40298.        ,  9834.08790437, 14881.4642027 ,
       14255.33718379,  9434.85885724,  7436.8152423 , 11630.59132818,
       10320.49463321,  5121.55098298,  9122.04240233, 28086.        ,
       35350.        , 15524.23227693, 30040.        ,  8364.73991311,
        4169.41628705,  3483.41746387, 36654.        , 11496.5092469 ,
        7996.75691111, 12664.429201  , 12645.07312307, 10777.00245785,
       15678.46117433, 31924.96812988,  9786.42971711,  8086.70978681,
        6044.23750812,  7636.90662274, 13846.74363362, 14125.92837937,
        7047.04299337, 19334.06314165, 19849.99963847, 38004.61854154,
       40026.        , 11557.49042145, 40842.        ,  7512.01709042,
        3234.77360269, 31034.        ,  8629.84442354, 27354.        ,
       11758.55827078,  6676.8293675 ,  2979.09239435, 10913.38163337,
         863.29654557, 10226.55553664,  6468.34791512, 32822.        ,
        9336.11022517,  5465.94085215,  6057.36343889,  8017.83384947,
       33598.        ,  3191.93632382, 36350.        ,  4898.56638136,
       14250.63893325, 13317.07728442, 10325.01948132, 32866.        ,
       17499.89231416, 17237.65026635, 32174.        , 39494.        ,
       12598.39556785, 10544.        ,   882.77116474, 19257.04085898,
       36466.        , 15115.62813547,  6498.94359188,  3664.14488627,
       37330.        , 29174.        , 31608.        ,  9018.2818856 ,
       12842.29131132, 13189.34525945, 12305.46331022, 19613.50076376,
       29846.        ,  6883.29339533,  3733.63619536,  9607.20781086,
       13726.44161132,  5244.82545217, 33032.        , 36862.        ,
       10898.4253743 , 33434.        , 17272.76439348,  7673.02089702,
        6857.0583589 ,  1226.34096809, 13488.65791984,  9033.69232452,
       11167.2760968 ,  7728.50747775, 19547.95669191, 10848.9680707 ,
        7169.39080273,  9557.3026895 , 10919.54060178, 35184.        ,
       11769.30147904, 31388.37441221, 11879.55646293,  5659.60465459,
        6100.69424234, 31544.        , 13436.99953866, 12723.66202948,
        9347.37761234, 30290.        , 35442.        , 16409.14151041,
        9517.01053156,  3134.9080575 , 18093.79945479, 17654.83667132,
       11973.30212147,  1626.78499746,  8385.84412464, 38776.11044003,
       15290.25399909, 14496.96337984,  8121.07752444, 30158.        ,
       17048.19402501, 38218.        , 31398.        ,  8783.00645482,
       15979.67266209, 10298.58623605, 13844.76196047,  5882.17352333,
        6713.67727008,  7996.45532806, 10311.41545082,  5262.48342142,
        1844.98135893,  6142.82800939,  5224.04166288,  7434.1358686 ,
        7533.56418263,  3784.10835875,  3698.85191629, 20281.16575129,
       32262.        ,  9476.60833574, 12155.0991135 , 13794.78168926,
        8871.96510242, 10383.63958827, 10983.89819846,  3089.71079683,
       11919.15031616, 26188.46690313, 14972.6217642 ,  9204.65652469,
       28457.78913658, 15680.39744672,  4280.29477563,  6871.91073238,
       12774.33717042, 17005.54343532, 36100.        , 32390.        ,
       12104.76061809, 29878.        ,  5121.71145458, 10840.35097527,
        9040.38163948, 13545.71140305, 38918.89425113, 14666.74170445,
       28362.        , 26286.        , 39082.        , 16106.45773359])

In [25]:
# Avaliar métricas do modelo
rmse = root_mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

In [26]:
# Mostrar as métricas
print(f'Root Mean Squared Error: {rmse}')
print(f'R2: {r2}')

Root Mean Squared Error: 6938.596010147248
R2: 0.7231228220148695