In [24]:
# Importar bibliotecas

import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go

from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.ensemble import BaggingRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import root_mean_squared_error, r2_score

# Carregar Dados

In [12]:
# carregar os dados
df_costs = pd.read_csv('datasets/healthcosts.csv')

In [13]:
df_costs.head(10)

   age     sex     bmi  children smoker     region  medical charges
0   19  female  27.900         0    yes  southwest      16884.92400
1   18    male  33.770         1     no  southeast       1725.55230
2   28    male  33.000         3     no  southeast       4449.46200
3   33    male  22.705         0     no  northwest      21984.47061
4   32    male  28.880         0     no  northwest       3866.85520
5   31  female  25.740         0     no  southeast       3756.62160
6   46  female  33.440         1     no  southeast       8240.58960
7   37  female  27.740         3     no  northwest       7281.50560
8   37    male  29.830         2     no  northeast       6406.41070
9   60  female  25.840         0     no  northwest      28923.13692

In [14]:
df_costs.tail(10)

      age     sex     bmi  children smoker     region  medical charges
1328   23  female  24.225         2     no  northeast      22395.74424
1329   52    male  38.600         2     no  southwest      10325.20600
1330   57  female  25.740         2     no  southeast      12629.16560
1331   23  female  33.400         0     no  southwest      10795.93733
1332   52  female  44.700         3     no  southwest      11411.68500
1333   50    male  30.970         3     no  northwest      10600.54830
1334   18  female  31.920         0     no  northeast       2205.98080
1335   18  female  36.850         0     no  southeast       1629.83350
1336   21  female  25.800         0     no  southwest       2007.94500
1337   61  female  29.070         0    yes  northwest      29141.36030

In [15]:
# Mostrar estrutura
df_costs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   age              1338 non-null   int64
 1   sex              1338 non-null   object
 2   bmi              1338 non-null   float64
 3   children         1338 non-null   int64
 4   smoker           1338 non-null   object
 5   region           1338 non-null   object
 6   medical charges  1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

# Feature Engineering

In [16]:
# Mostrar e remover as colunas categoricas que possuem somente um valor possível
for column in df_costs.select_dtypes(include=['object']).columns:
    if df_costs[column].nunique() == 1:
        print(f'Coluna {column} possui somente um valor possível: {df_costs[column].unique()}')

In [17]:
# Mostrar os valores possíveis para todas as colunas categoricas
for column in df_costs.select_dtypes(include=['object']).columns:
    print(f'Coluna {column} possui estes valores: {df_costs[column].unique()}')

Coluna sex possui estes valores: ['female' 'male']
Coluna smoker possui estes valores: ['yes' 'no']
Coluna region possui estes valores: ['southwest' 'southeast' 'northwest' 'northeast']

In [18]:
# Mostrar o percentual de valores ausentes para as colunas categoricas
for column in df_costs.select_dtypes(include=['object']).columns:
    contagem_nulas = df_costs[column].isnull().sum()
    print(f'{column}: {contagem_nulas / len(df_costs) * 100:.2f}%')

sex: 0.00%
smoker: 0.00%
region: 0.00%

In [19]:
# Apresentar Estatísticas Descritivas
df_costs.describe()

               age          bmi     children  medical charges
count  1338.000000  1338.000000  1338.000000      1338.000000
mean     39.207025    30.663397     1.094918     13270.422265
std      14.049960     6.098187     1.205493     12110.011237
min      18.000000    15.960000     0.000000      1121.873900
25%      27.000000    26.296250     0.000000      4740.287150
50%      39.000000    30.400000     1.000000      9382.033000
75%      51.000000    34.693750     2.000000     16639.912515
max      64.000000    53.130000     5.000000     63770.428010

In [20]:
# Mostrar e remover as colunas numericas que possuem somente um valor possível
for column in df_costs.select_dtypes(include=['number']).columns:
    if df_costs[column].nunique() == 1:
        print(f'Coluna {column} possui somente um valor possível: {df_costs[column].unique()}')

In [21]:
# Mostrar o percentual de valores ausentes para as colunas numericas
for column in df_costs.select_dtypes(include=['number']).columns:
    contagem_nulas = df_costs[column].isnull().sum()
    print(f'{column}: {contagem_nulas / len(df_costs) * 100:.2f}%')

age: 0.00%
bmi: 0.00%
children: 0.00%
medical charges: 0.00%

In [22]:
# Converter colunas categoricas com valores Yes e No para 1 e 0
for column in df_costs.select_dtypes(include=['object']).columns:
    valores_unicos = df_costs[column].unique()
    if set(valores_unicos).issubset(set(['yes', 'no'])):
        df_costs[column] = df_costs[column].apply(lambda x: 1 if x == 'yes' else 0)