In [11]:
# EDA
import pandas as pd
import plotly.express as px
import numpy as np

# Machine Learning
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, ElasticNet
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import VotingRegressor
from sklearn.metrics import root_mean_squared_error, r2_score

# Carregar os dados

In [12]:
# Carregar os dados já tratados
df_costs = pd.read_csv('datasets/healthcosts_cleaned.csv')

In [13]:
# Mostrar as primeiras linhas
df_costs.head(10)

   age     sex     bmi  children  smoker     region  medical charges
0   19  female  27.900         0       1  southwest      16884.92400
1   18    male  33.770         1       0  southeast       1725.55230
2   28    male  33.000         3       0  southeast       4449.46200
3   33    male  22.705         0       0  northwest      21984.47061
4   32    male  28.880         0       0  northwest       3866.85520
5   31  female  25.740         0       0  southeast       3756.62160
6   46  female  33.440         1       0  southeast       8240.58960
7   37  female  27.740         3       0  northwest       7281.50560
8   37    male  29.830         2       0  northeast       6406.41070
9   60  female  25.840         0       0  northwest      28923.13692

In [14]:
# Mostrar as últimas linhas
df_costs.tail(10)

      age     sex     bmi  children  smoker     region  medical charges
1328   23  female  24.225         2       0  northeast      22395.74424
1329   52    male  38.600         2       0  southwest      10325.20600
1330   57  female  25.740         2       0  southeast      12629.16560
1331   23  female  33.400         0       0  southwest      10795.93733
1332   52  female  44.700         3       0  southwest      11411.68500
1333   50    male  30.970         3       0  northwest      10600.54830
1334   18  female  31.920         0       0  northeast       2205.98080
1335   18  female  36.850         0       0  southeast       1629.83350
1336   21  female  25.800         0       0  southwest       2007.94500
1337   61  female  29.070         0       1  northwest      29141.36030

In [15]:
# Mostrar a estrutura
df_costs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   age              1338 non-null   int64
 1   sex              1338 non-null   object
 2   bmi              1338 non-null   float64
 3   children         1338 non-null   int64
 4   smoker           1338 non-null   int64
 5   region           1338 non-null   object
 6   medical charges  1338 non-null   float64
dtypes: float64(2), int64(3), object(2)
memory usage: 73.3+ KB

# Preparação dos dados

In [16]:
# Preparar dados - Separar X e y
X = df_costs.drop(columns=['medical charges'])
y = df_costs['medical charges']

In [17]:
# Carregar o preprocessor
import joblib
preprocessor = joblib.load('./preprocessor_dataset_healthcosts.pkl')

In [18]:
# Dividir o dataset entre treinamento e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=51)

In [19]:
# Aplicar o preprocessor
X_train = preprocessor.fit_transform(X_train)
X_test = preprocessor.transform(X_test)

In [20]:
# Mostrar os conjuntos
print(f'Dados de Treinamento: {X_train.shape}')
print(f'Dados de Teste: {X_test.shape}')

Dados de Treinamento: (1070, 10)
Dados de Teste: (268, 10)

# Treinamento do Modelo

In [21]:
# Criar o objeto de Voting Regressor

lr_model = LinearRegression()
elastic_model = ElasticNet(alpha=1.0, l1_ratio=0.5, random_state=51)
tree_model = DecisionTreeRegressor(random_state=51)

voting_model = VotingRegressor(
    estimators = [
        ('linear regression', lr_model),
        ('elastic', elastic_model),
        ('decision tree', tree_model)
    ]
)

In [22]:
# Treinar o modelo
voting_model.fit(X_train, y_train)

VotingRegressor(estimators=[('linear regression', LinearRegression()),
                            ('elastic', ElasticNet(random_state=51)),
                            ('decision tree',
                             DecisionTreeRegressor(random_state=51))])

# Análise dos Resultados

In [23]:
# Realizar predição
y_pred = voting_model.predict(X_test)

In [24]:
# Mostrar y_pred
y_pred

array([ 9217.84324756, 37008.214315  , 11374.79944306, 16485.61643585,
       33523.57959374, 10906.60829277, 10064.0759939 , 13477.43213162,
        6694.5196024 , 10752.12413053,  9771.71722238, 11907.44614343,
        9129.69381172,  4375.84816398,  6123.13714659, 12766.66608398,
        5319.70147364,  6695.69784269, 21274.99480695, 23775.14628505,
        8613.78215304,  8299.29664822, 39009.59959457, 12426.10054886,
        6734.49655255, 15296.52943612, 11179.1244833 ,  3443.09667158,
       25436.86646569, 13841.41995046,  4176.2838956 , 25488.93614715,
        5082.43165229,  4973.21922747,  8101.31767983, 17187.85388374,
       11101.76416801,  3225.96291261, 11995.47851548,  8504.09366477,
       10921.75504986,  2528.38099281,  5951.93808847,  3462.8632558 ,
        8573.32174675, 13874.14421414, 13674.59485872, 34620.28987138,
        9023.51974679, 12615.034391  ,  6281.90485212, 31672.17680155,
        8470.61413631, 39976.86061535, 11497.03043224, 28412.58005401,
        9349.48225239, 11323.92062784, 12525.98980776,  8112.6112403 ,
        9425.42480271,  8718.66776626, 26421.63068305,  2704.80173172,
       14213.64484587, 11273.0701242 , 12509.69577098,  5300.6561116 ,
       14467.06594557,  7561.71379568, 28988.90534542, 14809.3656235 ,
        6272.44843449,  5063.07604167, 13425.84962506, 11362.23149541,
       19361.49959849, 37242.13095028,  7876.1977472 ,  9926.3775348 ,
        4595.169452  , 11569.48237564,  9988.41011622,  3943.92016287,
        7366.41242323, 39726.10300815,  6531.76290972, 12115.1068368 ,
       12963.58875643,  6976.33352203,  6214.91052741, 17268.08649077,
        8237.35991354, 11060.13781788,  8240.8381195 , 22926.38574761,
       34376.52847373, 13094.75046874, 23524.89048602,  8158.29781403,
        3764.45796215,  2953.99207504, 35474.41822084,  8604.02341583,
        6339.48073788,  9537.01992776,  9257.9111175 ,  9018.5339748 ,
       11804.88801722, 31851.61641489,  8300.15119851,  7556.76460058,
        5339.54440772,  8638.41155828, 12232.99912531, 11553.50614572,
        5131.69788113, 15371.86988047, 15794.9935025 , 32925.61764403,
       38750.63294175,  8327.5757109 , 39981.05976784,  8455.74641941,
        2818.43267367, 25311.75852619,  5901.41896012, 28752.08868165,
        9480.44790343,  4614.16890608,  2719.41130481,  7898.13544831,
        1335.74271996,  8587.10533061,  5092.96354637, 27113.10800183,
       11955.72673203,  6103.03173239,  4621.53140252, 11047.86566387,
       33136.37690891,  2431.20785045, 35233.41547313,  3475.18192754,
       10892.59775498, 11555.40555597, 10178.89790149, 26656.20104479,
       14474.93974445, 19489.61211698, 38787.88683602, 38862.74080211,
        9873.67883573, 14048.82147616,  1381.38610287, 14353.70582635,
       28705.43117962, 12303.1715358 ,  4638.61426524,  3328.9130601 ,
       35922.75887303, 23657.70294278, 24901.38639546, 11645.81766965,
        9900.55214231, 11355.50802386, 12314.44285637, 15350.90850863,
       29356.52321385,  5132.15670662,  3096.19525422,  6322.62927594,
       12485.90831543,  4339.50425347, 30736.5625769 , 30040.19456174,
        8610.51084313, 33692.15105483, 16553.157273  ,  6423.84755422,
        6123.34126948,  1542.25330245, 11302.17740023,  8435.11566831,
       10600.52332416,  6833.58122561, 13620.28102197,  7913.99156706,
        5833.07510212,  8916.09779644,  9699.99555383, 28422.68834317,
        9357.65686395, 25788.41142457, 14052.9720975 ,  6167.96645309,
        4436.31706452, 25597.00885797, 12200.39050417, 10373.30550684,
        7631.36397842, 30701.98350714, 34449.41213198, 13081.19962567,
       14480.40330076,  2559.25720303, 14908.56907708, 14126.29236039,
        9181.10231565,  1693.2253857 ,  6212.02017722, 37104.89691957,
       13112.94761479, 13095.12569442,  6175.01889254, 24411.10483291,
       22228.11912693, 37720.94391701, 31755.15973026,  6948.24698052,
       12887.86960864,  7767.5156751 , 11451.53208546,  4571.07855275,
        6561.58117454,  6779.90634991,  8566.59330536,  4667.94194866,
        9014.16942458,  8664.08163047,  4068.02872579,  4613.19829266,
        7004.46594104,  3364.88360409,  3454.02311984, 15486.98109155,
       26788.33790153,  6508.57614741,  9793.70401979, 13406.18807844,
        7791.76889567, 15151.3924613 ,  8367.9129057 ,  2750.51096718,
        9853.09773853, 26512.00490958, 11396.98886769,  6649.60806766,
       21891.88618927, 12855.82299616,  2975.56629872,  5440.3191349 ,
        7118.31910752, 13221.93749333, 39402.17403765, 32049.99611919,
       10190.17193137, 24252.4566423 ,  4374.71663223, 12664.97890912,
        6206.13775649, 10200.55650148, 38642.50271041, 10902.3238773 ,
       28729.65497198, 27184.40349311, 38131.37606406, 13849.16077432])

In [25]:
# Avaliar métricas do modelo
rmse = root_mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

In [26]:
# Mostrar o Erro e R2 do Modelo
print(f'RMSE {rmse}')
print(f'R2 {r2}')

RMSE 6240.904728783782
R2 0.7760046197139258