In [3]:
# EDA
import pandas as pd
import plotly.express as px
import numpy as np

# Machine Learning
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# Carregar Dados

In [4]:
# Carregar o dataset já tratado
df_leads = pd.read_csv('./datasets/leads_cleaned.csv')

In [5]:
# Mostrar as primeiras linhas
df_leads.head(10)

,Lead Origin,Lead Source,Do Not Email,Do Not Call,Converted,TotalVisits,Total Time Spent on Website,Page Views Per Visit,Last Activity,Search,Newspaper Article,X Education Forums,Newspaper,Digital Advertisement,Through Recommendations,A free copy of Mastering The Interview,Last Notable Activity
0,API,Olark Chat,0,0,0,0.0,0,0.0,Page Visited on Website,0,0,0,0,0,0,0,Modified
1,API,Organic Search,0,0,0,5.0,674,2.5,Email Opened,0,0,0,0,0,0,0,Email Opened
2,Landing Page Submission,Direct Traffic,0,0,1,2.0,1532,2.0,Email Opened,0,0,0,0,0,0,1,Email Opened
3,Landing Page Submission,Direct Traffic,0,0,0,1.0,305,1.0,Unreachable,0,0,0,0,0,0,0,Modified
4,Landing Page Submission,Google,0,0,1,2.0,1428,1.0,Converted to Lead,0,0,0,0,0,0,0,Modified
5,API,Olark Chat,0,0,0,0.0,0,0.0,Olark Chat Conversation,0,0,0,0,0,0,0,Modified
6,Landing Page Submission,Google,0,0,1,2.0,1640,2.0,Email Opened,0,0,0,0,0,0,0,Modified
7,API,Olark Chat,0,0,0,0.0,0,0.0,Olark Chat Conversation,0,0,0,0,0,0,0,Modified
8,Landing Page Submission,Direct Traffic,0,0,0,2.0,71,2.0,Email Opened,0,0,0,0,0,0,1,Email Opened
9,API,Google,0,0,0,4.0,58,4.0,Email Opened,0,0,0,0,0,0,0,Email Opened

In [6]:
# Mostrar as últimas linhas
df_leads.tail(10)

,Lead Origin,Lead Source,Do Not Email,Do Not Call,Converted,TotalVisits,Total Time Spent on Website,Page Views Per Visit,Last Activity,Search,Newspaper Article,X Education Forums,Newspaper,Digital Advertisement,Through Recommendations,A free copy of Mastering The Interview,Last Notable Activity
9064,Landing Page Submission,Google,0,0,0,2.0,870,2.00,Email Opened,0,0,0,0,0,0,0,Email Opened
9065,Landing Page Submission,Google,0,0,1,8.0,1016,4.00,Email Opened,0,0,0,0,0,0,0,Email Opened
9066,Landing Page Submission,Direct Traffic,0,0,0,2.0,1770,2.00,SMS Sent,0,0,0,0,0,0,1,SMS Sent
9067,API,Direct Traffic,0,0,1,13.0,1409,2.60,SMS Sent,0,0,0,0,0,0,0,SMS Sent
9068,Landing Page Submission,Direct Traffic,0,0,1,5.0,210,2.50,SMS Sent,0,0,0,0,0,0,0,Modified
9069,Landing Page Submission,Direct Traffic,1,0,1,8.0,1845,2.67,Email Marked Spam,0,0,0,0,0,0,0,Email Marked Spam
9070,Landing Page Submission,Direct Traffic,0,0,0,2.0,238,2.00,SMS Sent,0,0,0,0,0,0,1,SMS Sent
9071,Landing Page Submission,Direct Traffic,1,0,0,2.0,199,2.00,SMS Sent,0,0,0,0,0,0,1,SMS Sent
9072,Landing Page Submission,Google,0,0,1,3.0,499,3.00,SMS Sent,0,0,0,0,0,0,0,SMS Sent
9073,Landing Page Submission,Direct Traffic,0,0,1,6.0,1279,3.00,SMS Sent,0,0,0,0,0,0,1,Modified

In [7]:
# Mostrar estrutura do Dataset
df_leads.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9074 entries, 0 to 9073
Data columns (total 17 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Lead Origin                             9074 non-null   object
 1   Lead Source                             9074 non-null   object
 2   Do Not Email                            9074 non-null   int64
 3   Do Not Call                             9074 non-null   int64
 4   Converted                               9074 non-null   int64
 5   TotalVisits                             9074 non-null   float64
 6   Total Time Spent on Website             9074 non-null   int64
 7   Page Views Per Visit                    9074 non-null   float64
 8   Last Activity                           9074 non-null   object
 9   Search                                  9074 non-null   int64
 10  Newspaper Article                       9074 non-null   int64
 11  X Education Forums                      9074 non-null   int64
 12  Newspaper                               9074 non-null   int64
 13  Digital Advertisement                   9074 non-null   int64
 14  Through Recommendations                 9074 non-null   int64
 15  A free copy of Mastering The Interview  9074 non-null   int64
 16  Last Notable Activity                   9074 non-null   object
dtypes: float64(2), int64(11), object(4)
memory usage: 1.2+ MB

# Preparação dos dados

In [8]:
# Preparar os dados (X e y)
X = df_leads.drop(columns=['Converted'])
y = df_leads['Converted']

In [9]:
# Usar Preprocessor já salvo
import joblib
preprocessor = joblib.load('./preprocessor_dataset_leads.pkl')

In [10]:
# Dividir dataset entre treinamento e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=51)

# Aplicar preprocessor
X_train = preprocessor.fit_transform(X_train).toarray()
X_test = preprocessor.transform(X_test).toarray()

In [11]:
# Mostrar a estrutura dos conjuntos
print(f'Conjunto de Treinamento: {X_train.shape}')
print(f'Conjunto de testes: {X_test.shape}')

Conjunto de Treinamento: (7259, 68)
Conjunto de testes: (1815, 68)

In [12]:
preprocessor.get_feature_names_out()

array(['num__Do Not Email', 'num__Do Not Call', 'num__TotalVisits',
       'num__Total Time Spent on Website', 'num__Page Views Per Visit',
       'num__Search', 'num__Newspaper Article', 'num__X Education Forums',
       'num__Newspaper', 'num__Digital Advertisement',
       'num__Through Recommendations',
       'num__A free copy of Mastering The Interview',
       'cat__Lead Origin_API', 'cat__Lead Origin_Landing Page Submission',
       'cat__Lead Origin_Lead Add Form', 'cat__Lead Origin_Lead Import',
       'cat__Lead Source_Click2call', 'cat__Lead Source_Direct Traffic',
       'cat__Lead Source_Facebook', 'cat__Lead Source_Google',
       'cat__Lead Source_Live Chat', 'cat__Lead Source_NC_EDM',
       'cat__Lead Source_Olark Chat', 'cat__Lead Source_Organic Search',
       'cat__Lead Source_Pay per Click Ads', 'cat__Lead Source_Reference',
       'cat__Lead Source_Referral Sites', 'cat__Lead Source_Social Media',
       'cat__Lead Source_WeLearn', 'cat__Lead Source_Welingak Website',
       'cat__Lead Source_bing', 'cat__Lead Source_blog',
       'cat__Lead Source_testone', 'cat__Lead Source_welearnblog_Home',
       'cat__Lead Source_youtubechannel',
       'cat__Last Activity_Approached upfront',
       'cat__Last Activity_Converted to Lead',
       'cat__Last Activity_Email Bounced',
       'cat__Last Activity_Email Link Clicked',
       'cat__Last Activity_Email Marked Spam',
       'cat__Last Activity_Email Opened',
       'cat__Last Activity_Email Received',
       'cat__Last Activity_Form Submitted on Website',
       'cat__Last Activity_Had a Phone Conversation',
       'cat__Last Activity_Olark Chat Conversation',
       'cat__Last Activity_Page Visited on Website',
       'cat__Last Activity_Resubscribed to emails',
       'cat__Last Activity_SMS Sent', 'cat__Last Activity_Unreachable',
       'cat__Last Activity_Unsubscribed',
       'cat__Last Activity_View in browser link Clicked',
       'cat__Last Activity_Visited Booth in Tradeshow',
       'cat__Last Notable Activity_Approached upfront',
       'cat__Last Notable Activity_Email Bounced',
       'cat__Last Notable Activity_Email Link Clicked',
       'cat__Last Notable Activity_Email Marked Spam',
       'cat__Last Notable Activity_Email Opened',
       'cat__Last Notable Activity_Email Received',
       'cat__Last Notable Activity_Form Submitted on Website',
       'cat__Last Notable Activity_Had a Phone Conversation',
       'cat__Last Notable Activity_Modified',
       'cat__Last Notable Activity_Olark Chat Conversation',
       'cat__Last Notable Activity_Page Visited on Website',
       'cat__Last Notable Activity_Resubscribed to emails',
       'cat__Last Notable Activity_SMS Sent',
       'cat__Last Notable Activity_Unreachable',
       'cat__Last Notable Activity_Unsubscribed',
       'cat__Last Notable Activity_View in browser link Clicked'],
      dtype=object)

# Treinamento do Modelo de Voting Classifier

In [13]:
# Criar o modelo de VotingClassifier

lr_model = LogisticRegression(random_state=51)
svc_model = SVC(kernel='linear')
tree_model = DecisionTreeClassifier(random_state=51)

voting_model_hard = VotingClassifier(
    estimators = [
        ('logistic regression', lr_model),
        ('svc', svc_model),
        ('decision tree', tree_model)
    ],
    # Hard faz a votação pela maioria das predições dos estimadores
    # Soft faz a votação pela média das probabilidades de cada classe vindas de cada estimador
    voting='hard'
)

In [14]:
# Treinar o modelo
voting_model_hard.fit(X_train, y_train)

VotingClassifier(estimators=[('logistic regression',
                              LogisticRegression(random_state=51)),
                             ('svc', SVC(kernel='linear')),
                             ('decision tree',
                              DecisionTreeClassifier(random_state=51))])

# Análise dos Resultados

In [48]:
# Realizar predições no conjunto de testes
y_pred = voting_model_hard.predict(X_test)

In [50]:
# Calcular métricas
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

In [51]:
# Mostrar métricas
print(f'Acurácia: {accuracy}')
print(f'Precisão: {precision}')
print(f'Recall: {recall}')
print(f'F1 Score: {f1}')

Acurácia: 0.7983471074380165
Precisão: 0.7420382165605095
Recall: 0.6955223880597015
F1 Score: 0.7180277349768875

In [52]:
# Mostrar a matriz de confusão
conf_matrix = confusion_matrix(y_test, y_pred)

fig = px.imshow(conf_matrix,
                labels=dict(x='Predição', y='Real', color='Contagem'),
                x=['Not Converted', 'Converted'],
                y=['Not Converted', 'Converted'],
                color_continuous_scale='Viridis')

fig.update_traces(text=conf_matrix, texttemplate="%{z}")
fig.update_layout(coloraxis_showscale=False)

fig.show()

## Análise de Importância

In [19]:
# Carregar as importâncias dos modelos

importances = []

for estimador in voting_model_hard.estimators_:
    # Pra modelos lineares, retorna coef
    if hasattr(estimador, 'coef_'):
        importances.append(np.abs(estimador.coef_[0]))
    # Para modelos baseados em árvores
    elif hasattr(estimador, 'feature_importances_'):
        importances.append(estimador.feature_importances_)
    else:
        print(f'Não foi possível carregar as importâncias do modelo {type(estimador).__name__}')

In [20]:
# Calcular a média das importâncias
importancia_media = np.mean(importances, axis=0)

In [21]:
# Nomes das features
feature_names = preprocessor.get_feature_names_out()

In [22]:
# Criar um Dataframe com nomes e importâncias das features
df_feature_importances = pd.DataFrame({'Feature': feature_names, 'Importance': importancia_media})

In [23]:
# Ordenar o Dataframe pela importância
df_feature_importances = df_feature_importances.sort_values(by='Importance', ascending=True)

In [24]:
# Plotar a importância das features
fig = px.bar(df_feature_importances,
             x='Importance',
             y='Feature',
             orientation='h',
             title='Importância das Features (Voting Classifier)'
             )

fig.update_layout(height=1280, width=1000)

fig.show()