In [ ]:
import pandas as pd
import numpy as np
import plotly.express as px
pd.set_option('display.float_format', lambda x: '%.2f' % x)
np.set_printoptions(precision=10, suppress=True)

from sklearn.mixture import GaussianMixture
from sklearn.preprocessing import StandardScaler, OneHotEncoder, OrdinalEncoder
from sklearn.compose import ColumnTransformer

import optuna

# Carregar os Dados

In [2]:
df_clientes = pd.read_csv('datasets/dataset_clientes_pj.csv')

In [5]:
# Visualizar as colunas
df_clientes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   atividade_economica     500 non-null    object
 1   faturamento_mensal      500 non-null    float64
 2   numero_de_funcionarios  500 non-null    int64
 3   localizacao             500 non-null    object
 4   idade                   500 non-null    int64
 5   inovacao                500 non-null    int64
dtypes: float64(1), int64(3), object(2)
memory usage: 23.6+ KB

In [6]:
# Visualizar os 10 primeiros registros
df_clientes.head(10)

,atividade_economica,faturamento_mensal,numero_de_funcionarios,localizacao,idade,inovacao
0,Comércio,713109.95,12,Rio de Janeiro,6,1
1,Comércio,790714.38,9,São Paulo,15,0
2,Comércio,1197239.33,17,São Paulo,4,9
3,Indústria,449185.78,15,São Paulo,6,0
4,Agronegócio,1006373.16,15,São Paulo,15,8
5,Serviços,1629562.41,16,Rio de Janeiro,11,4
6,Serviços,771179.95,13,Vitória,0,1
7,Serviços,707837.61,16,São Paulo,10,6
8,Comércio,888983.66,17,Belo Horizonte,10,1
9,Indústria,1098512.64,13,Rio de Janeiro,9,3

In [7]:
# Visualizar os 10 ultimos registros
df_clientes.tail(10)

,atividade_economica,faturamento_mensal,numero_de_funcionarios,localizacao,idade,inovacao
490,Indústria,215580.61,11,Belo Horizonte,7,3
491,Serviços,1050776.57,14,Vitória,8,0
492,Comércio,785671.05,15,Vitória,9,2
493,Serviços,658330.45,20,Belo Horizonte,4,8
494,Agronegócio,1643153.26,14,Rio de Janeiro,10,1
495,Serviços,1581841.42,17,Rio de Janeiro,8,2
496,Indústria,1291309.57,9,São Paulo,6,9
497,Serviços,2211489.85,10,Belo Horizonte,10,0
498,Agronegócio,1460860.46,12,Rio de Janeiro,5,3
499,Indústria,173684.43,13,Belo Horizonte,4,9

In [8]:
# Medidas estatisticas
df_clientes.describe()

       faturamento_mensal  numero_de_funcionarios  idade  inovacao
count              500.00                  500.00 500.00    500.00
mean           1026715.63                   13.69   9.25      4.39
std             420609.46                    3.12   2.96      2.90
min              18421.22                    2.00   0.00      0.00
25%             763253.58                   12.00   7.00      2.00
50%            1022957.08                   14.00   9.00      4.00
75%            1295888.52                   16.00  11.00      7.00
max            2390677.22                   21.00  16.00      9.00