# Consulte o arquivo Readme.md para obter detalhes sobre o desafio

[Readme.md](Readme.md)

In [25]:
# Importar as bibliotecas

# EDA
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
import numpy as np
from scipy.stats import chi2_contingency

In [26]:
df_airline = pd.read_csv('datasets/airline_train.csv')
df_airline_test = pd.read_csv('datasets/airline_test.csv')

In [27]:
df_airline.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103904 entries, 0 to 103903
Data columns (total 25 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   Unnamed: 0                         103904 non-null  int64
 1   id                                 103904 non-null  int64
 2   Gender                             103904 non-null  object
 3   Customer Type                      103904 non-null  object
 4   Age                                103904 non-null  int64
 5   Type of Travel                     103904 non-null  object
 6   Class                              103904 non-null  object
 7   Flight Distance                    103904 non-null  int64
 8   Inflight wifi service              103904 non-null  int64
 9   Departure/Arrival time convenient  103904 non-null  int64
 10  Ease of Online booking             103904 non-null  int64
 11  Gate location                      103904 non-null  int64
 12  Food and drink                     103904 non-null  int64
 13  Online boarding                    103904 non-null  int64
 14  Seat comfort                       103904 non-null  int64
 15  Inflight entertainment             103904 non-null  int64
 16  On-board service                   103904 non-null  int64
 17  Leg room service                   103904 non-null  int64
 18  Baggage handling                   103904 non-null  int64
 19  Checkin service                    103904 non-null  int64
 20  Inflight service                   103904 non-null  int64
 21  Cleanliness                        103904 non-null  int64
 22  Departure Delay in Minutes         103904 non-null  int64
 23  Arrival Delay in Minutes           103594 non-null  float64
 24  satisfaction                       103904 non-null  object
dtypes: float64(1), int64(19), object(5)
memory usage: 19.8+ MB

In [28]:
df_airline.isnull().sum()

Unnamed: 0                             0
id                                     0
Gender                                 0
Customer Type                          0
Age                                    0
Type of Travel                         0
Class                                  0
Flight Distance                        0
Inflight wifi service                  0
Departure/Arrival time convenient      0
Ease of Online booking                 0
Gate location                          0
Food and drink                         0
Online boarding                        0
Seat comfort                           0
Inflight entertainment                 0
On-board service                       0
Leg room service                       0
Baggage handling                       0
Checkin service                        0
Inflight service                       0
Cleanliness                            0
Departure Delay in Minutes             0
Arrival Delay in Minutes             310
satisfaction                           0
dtype: int64

In [29]:
df_airline_test.isnull().sum()

Unnamed: 0                            0
id                                    0
Gender                                0
Customer Type                         0
Age                                   0
Type of Travel                        0
Class                                 0
Flight Distance                       0
Inflight wifi service                 0
Departure/Arrival time convenient     0
Ease of Online booking                0
Gate location                         0
Food and drink                        0
Online boarding                       0
Seat comfort                          0
Inflight entertainment                0
On-board service                      0
Leg room service                      0
Baggage handling                      0
Checkin service                       0
Inflight service                      0
Cleanliness                           0
Departure Delay in Minutes            0
Arrival Delay in Minutes             83
satisfaction                          0
dtype: int64

In [30]:
df_airline[df_airline.isnull().any(axis=1)].head(10)

,Unnamed: 0,id,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,...,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,satisfaction
213,213,49608,Female,Loyal Customer,38,Business travel,Eco,109,5,3,...,5,5,2,4,1,1,5,31,NaN,satisfied
1124,1124,73442,Male,Loyal Customer,53,Personal Travel,Eco,1012,3,2,...,4,4,4,4,3,3,4,38,NaN,neutral or dissatisfied
1529,1529,71178,Male,Loyal Customer,39,Business travel,Business,733,2,5,...,2,2,2,2,2,2,3,11,NaN,neutral or dissatisfied
2004,2004,72940,Female,disloyal Customer,26,Business travel,Business,1035,3,3,...,2,3,3,4,5,5,2,41,NaN,neutral or dissatisfied
2108,2108,116374,Female,Loyal Customer,24,Personal Travel,Eco,417,2,1,...,5,1,4,2,1,2,5,1,NaN,neutral or dissatisfied
2485,2485,121173,Female,Loyal Customer,28,Personal Travel,Eco,2370,4,5,...,3,5,4,4,5,4,3,3,NaN,satisfied
2630,2630,3638,Male,Loyal Customer,35,Business travel,Business,1534,1,1,...,5,5,5,5,5,5,5,0,NaN,satisfied
3621,3621,48387,Male,Loyal Customer,47,Personal Travel,Eco,587,1,2,...,4,1,1,4,4,4,4,17,NaN,neutral or dissatisfied
4041,4041,66091,Male,Loyal Customer,31,Business travel,Business,2490,1,1,...,4,3,5,5,4,4,4,6,NaN,satisfied
4490,4490,48504,Male,disloyal Customer,30,Business travel,Eco,737,4,4,...,2,5,1,4,1,3,2,22,NaN,neutral or dissatisfied

In [31]:
# Remover a coluna Unnamed: 0 para ela não atrapalhar os processamentos
df_airline.drop(columns=['Unnamed: 0'], axis=1, inplace=True)

In [32]:
df_airline.head(10)

,id,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,...,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,satisfaction
0,70172,Male,Loyal Customer,13,Personal Travel,Eco Plus,460,3,4,3,...,5,4,3,4,4,5,5,25,18.0,neutral or dissatisfied
1,5047,Male,disloyal Customer,25,Business travel,Business,235,3,2,3,...,1,1,5,3,1,4,1,1,6.0,neutral or dissatisfied
2,110028,Female,Loyal Customer,26,Business travel,Business,1142,2,2,2,...,5,4,3,4,4,4,5,0,0.0,satisfied
3,24026,Female,Loyal Customer,25,Business travel,Business,562,2,5,5,...,2,2,5,3,1,4,2,11,9.0,neutral or dissatisfied
4,119299,Male,Loyal Customer,61,Business travel,Business,214,3,3,3,...,3,3,4,4,3,3,3,0,0.0,satisfied
5,111157,Female,Loyal Customer,26,Personal Travel,Eco,1180,3,4,2,...,1,3,4,4,4,4,1,0,0.0,neutral or dissatisfied
6,82113,Male,Loyal Customer,47,Personal Travel,Eco,1276,2,4,2,...,2,3,3,4,3,5,2,9,23.0,neutral or dissatisfied
7,96462,Female,Loyal Customer,52,Business travel,Business,2035,4,3,4,...,5,5,5,5,4,5,4,4,0.0,satisfied
8,79485,Female,Loyal Customer,41,Business travel,Business,853,1,2,2,...,1,1,2,1,4,1,2,0,0.0,neutral or dissatisfied
9,65725,Male,disloyal Customer,20,Business travel,Eco,1061,3,3,3,...,2,2,3,4,4,3,2,0,0.0,neutral or dissatisfied

In [33]:
# vamos verificar quantos ID únicos de clientes temos
df_airline['id'].nunique() , df_airline['id'].nunique() == len(df_airline)
# Temos então que nenhum ID de cliente se repete por todo o dataset

(103904, True)

In [34]:
# Distribuição da variável satisfation em percentual

fig = px.bar(df_airline['satisfaction'].value_counts() / len(df_airline) * 100, title='Hit Ratio - Satisfaction',labels={'index': 'Satisfaction', 'value': 'Percentual'})

fig.update_layout(showlegend=False)
fig.show()

In [35]:
# Distribuição da variável Gender em percentual

fig = px.bar(df_airline['Gender'].value_counts() / len(df_airline) * 100, title='Hit Ratio - Genero',labels={'index': 'Genero', 'value': 'Percentual'})

fig.update_layout(showlegend=False)
fig.show()

In [36]:
# Distribuição da variável Customer Type em percentual

fig = px.bar(df_airline['Customer Type'].value_counts() / len(df_airline) * 100, title='Hit Ratio - Customer Type',labels={'index': 'Customer Type', 'value': 'Percentual'})

fig.update_layout(showlegend=False)
fig.show()

In [37]:
# Distribuição da variável Type of Travel em percentual

fig = px.bar(df_airline['Type of Travel'].value_counts() / len(df_airline) * 100, title='Hit Ratio - Type of Travel',labels={'index': 'Type of Travel', 'value': 'Percentual'})

fig.update_layout(showlegend=False)
fig.show()

In [38]:
# Distribuição da variável Class em percentual

fig = px.bar(df_airline['Class'].value_counts() / len(df_airline) * 100, title='Hit Ratio - Class',labels={'index': 'Class', 'value': 'Percentual'})

fig.update_layout(showlegend=False)
fig.show()

In [39]:
# Distribuição da variável Inflight wifi service em percentual

fig = px.bar(df_airline['Inflight wifi service'].value_counts(), title='Hit Ratio - Inflight wifi service',labels={'index': 'Inflight wifi service', 'value': 'Percentual'})

fig.update_layout(showlegend=False)
fig.show()

In [40]:
# Histograma da variável Age

fig = px.histogram(df_airline, x='Age', nbins=20, title='Histograma da variável Age')
fig.update_layout(xaxis_title='Idade', yaxis_title='Frequência')
fig.show()

In [41]:
# Histograma da variável Flight Distance

fig = px.histogram(df_airline, x='Flight Distance', nbins=20, title='Histograma da variável Flight Distance')
fig.update_layout(xaxis_title='Distancia de Voo', yaxis_title='Frequência')
fig.show()

In [42]:
# Boxplot da variável Departure Delay in Minutes
fig = px.box(df_airline, y='Departure Delay in Minutes', title='Boxplot - Departure Delay in Minutes')
fig.update_layout(yaxis_title='Atraso para Saida')
fig.show()

In [43]:
# Boxplot da variável Arrival Delay in Minutes
fig = px.box(df_airline, y='Arrival Delay in Minutes', title='Boxplot - Arrival Delay in Minutes')
fig.update_layout(yaxis_title='Atraso para Chegada')
fig.show()

In [44]:
# Transformar a variável Satisfaction em 0 e 1 para matriz de correlação
df_airline['satisfaction'] = df_airline['satisfaction'].map({'satisfied': 1, 'neutral or dissatisfied': 0})

In [45]:
# Matriz de Correlação das variáveis numéricas
corr_matrix = df_airline.select_dtypes(include=['number']).corr()

In [46]:
# Plot de Correlação
fig = go.Figure()

fig.add_trace(
    go.Heatmap(
        x = corr_matrix.columns,
        y = corr_matrix.index,
        z = np.array(corr_matrix),
        text = corr_matrix.values,
        texttemplate='%{text:.2f}',
        colorscale=px.colors.diverging.RdBu,
        zmin=-1,
        zmax=1
    )
)

fig.show()

In [47]:
# Distribuição da variável Online boarding em percentual

fig = px.bar(df_airline['Online boarding'].value_counts() / len(df_airline) * 100, title='Hit Ratio - Online boarding',labels={'index': 'Online boarding', 'value': 'Percentual'})

fig.update_layout(showlegend=False)
fig.show()

In [48]:
# Criar uma tabela de contingência de Online boarding x Satisfaction
contingency_table_lead_origin = pd.crosstab(df_airline['Online boarding'], df_airline['satisfaction'])

chi2, p, dof, expected = chi2_contingency(contingency_table_lead_origin)
# Mostrar o resultado
print(f'Estatística qui-quadrado: {chi2}')
print(f'Valor p: {p}')
print(f'Graus de Liberdade: {dof}')
print(f'Existe uma relação significativa entre Online boarding x Satisfaction? {"Sim" if p < 0.05 else "Não"}')

Estatística qui-quadrado: 39750.99560405667
Valor p: 0.0
Graus de Liberdade: 5
Existe uma relação significativa entre Online boarding x Satisfaction? Sim

In [49]:
# Criar uma tabela de contingência de Arrival Delay in Minutes x Departure Delay in Minutes
contingency_table_lead_origin = pd.crosstab(df_airline['Arrival Delay in Minutes'], df_airline['Departure Delay in Minutes'])

chi2, p, dof, expected = chi2_contingency(contingency_table_lead_origin)
# Mostrar o resultado
print(f'Estatística qui-quadrado: {chi2}')
print(f'Valor p: {p}')
print(f'Graus de Liberdade: {dof}')
print(f'Existe uma relação significativa entre Arrival Delay in Minutes x Departure Delay in Minutes? {"Sim" if p < 0.05 else "Não"}')

Estatística qui-quadrado: 13348190.601358425
Valor p: 0.0
Graus de Liberdade: 201576
Existe uma relação significativa entre Arrival Delay in Minutes x Departure Delay in Minutes? Sim